name: Build

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install Python requirements
        shell: bash
        run: >
          python -OO -m pip install --disable-pip-version-check --upgrade nuitka zstandard &&
            python -OO -m pip install --disable-pip-version-check -r requirements.txt
      - name: Build executable
        shell: powershell
        run: >
          python -OO -m nuitka --standalone --onefile --python-flag=-OO --assume-yes-for-downloads --static-libpython=auto --windows-icon-from-ico=nicestalker/resources/nightstalker.ico --windows-product-name=NiceStalker --windows-company-name=naghim --windows-file-version=1.0.0.0 --windows-file-description="NiceStalker Configurator" --enable-plugin=pyqt6 -o NiceStalker.exe gui/__main__.py
      - uses: actions/upload-artifact@v4
        with:
          name: NiceStalker
          path: |
            NiceStalkerConfigurator.exe
            NiceStalkerDaemon.exe
